spring.application.name=Blog-project
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:blog
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.show-sql=true

#Image/File configs
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

project.image=images/